[pytest]
addopts = --browser chromium --headed --alluredir=allure-results --clean-alluredir
; addopts = --browser chromium --alluredir=allure-results --clean-alluredir
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
